name: first workflow
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello Worlds! This is the first job
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: greet
        id : greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Manish'
          
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"    
        
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob 
    env:
      JOB_VAR: "This is job variable"
    steps:
      - name: secondJob script
        run: |
          echo this is the second job
          echo and this is a multi-line script
      - name: envjob   
        env:
          STEP_VAR: "This is step variable"
        run: 
          echo $STEP_VAR  
          
